import { SessionId } from '@deepseek-ai/dsh-session'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { WorkspaceFileObserver } from '../src/client/workspace-file-observer.ts'
import { deferred, flush, hostFilesFixture } from './fixtures/host-files.ts'
afterEach(() => vi.useRealTimers())
describe('native Host observation generations', () => {
  it('does not read before ready; invalidation resets pages to a new opaque version; close releases watch', async () => {
    const f = hostFilesFixture(), observer = new WorkspaceFileObserver('报告.md', f.options)
    await flush(); expect(f.calls).toEqual(['stat', 'watch']); expect(f.read).not.toHaveBeenCalled()
    f.feeds[0]!.push({ kind: 'ready' }); await flush()
    expect(f.calls).toEqual(['stat', 'watch', 'stat', 'read']); expect(observer.getSnapshot()).toMatchObject({ mode: 'watching', stale: false, page: { version: 'opaque-v1' } })
    f.setFile('opaque-v2', 'changed'); f.feeds[0]!.push({ kind: 'change', change: { absolutePath: '/synthetic-remote/workspace/报告.md', version: 'opaque-v2' } }); await flush()
    expect(observer.getSnapshot().page?.text).toBe('changed')
    const reads = f.read.mock.calls.length
    f.feeds[0]!.push({ kind: 'change', change: { absolutePath: '/synthetic-remote/workspace/报告.md', version: 'opaque-v2' } }); await flush(); expect(f.read).toHaveBeenCalledTimes(reads)
    observer.dispose(); await observer.closed(); expect(f.feeds[0]?.returns).toBe(1); expect(f.listeners.size).toBe(0)
  })
  it('truthfully falls back to manual refresh for unsupported SSH watch without retry/poll', async () => {
    const f = hostFilesFixture(); f.changes.mockRejectedValue(new Error('workspace-file/watch-unsupported: synthetic SSH provider'))
    const observer = new WorkspaceFileObserver('报告.md', f.options); await flush()
    expect(observer.getSnapshot()).toMatchObject({ mode: 'manual', reason: expect.stringContaining('watch-unsupported'), stale: false })
    expect(f.changes).toHaveBeenCalledTimes(1); f.setFile('opaque-v2', 'remote change'); await flush(); expect(f.read).toHaveBeenCalledTimes(1)
    observer.refresh(); await flush(); expect(observer.getSnapshot().page?.text).toBe('remote change'); expect(f.changes).toHaveBeenCalledTimes(1)
    observer.dispose(); await observer.closed()
  })
  it('missing watch uses manual reads; absent stat/read permission disables content', async () => {
    const f = hostFilesFixture(); f.gates.set('workspaceFiles/changes', undefined); f.gates.set('workspaceFiles/stat', { available: false, reason: 'Plugin disabled' })
    const observer = new WorkspaceFileObserver('报告.md', f.options); await flush()
    expect(observer.getSnapshot()).toMatchObject({ mode: 'manual', reason: expect.stringContaining('not confirmed'), error: 'Plugin disabled' }); expect(f.read).not.toHaveBeenCalled(); expect(f.changes).not.toHaveBeenCalled()
    observer.dispose(); await observer.closed()
  })
  it('disconnect suppresses late reads; reconnect waits for cleanup then watches and rereads after ready', async () => {
    const f = hostFilesFixture(), pending = deferred<Awaited<ReturnType<typeof f.read>>>()
    f.read.mockImplementationOnce(() => pending.promise)
    const observer = new WorkspaceFileObserver('报告.md', f.options); await flush(); f.feeds[0]!.push({ kind: 'ready' }); await flush()
    f.change({ ready: false }); await flush(); expect(observer.getSnapshot().mode).toBe('disconnected')
    f.change({ ready: true, generation: 2 }); await flush(); expect(f.feeds[0]?.closed).toBe(true); expect(f.feeds).toHaveLength(2); expect(f.read).toHaveBeenCalledTimes(1)
    pending.resolve({ ok: true, value: { absolutePath: '/synthetic-remote/workspace/报告.md', version: 'late', text: 'late', offset: 1, lines: 1, eof: true } }); await flush()
    expect(observer.getSnapshot().page).toBeUndefined()
    f.setFile('opaque-v2'); f.feeds[1]!.push({ kind: 'ready' }); await flush(); expect(observer.getSnapshot().page?.version).toBe('opaque-v2')
    observer.dispose(); await observer.closed()
  })
  it('coalesces changes arriving while an old read is pending and never publishes stale content', async () => {
    const f = hostFilesFixture(), pending = deferred<Awaited<ReturnType<typeof f.read>>>()
    f.read.mockImplementationOnce(() => pending.promise)
    const observer = new WorkspaceFileObserver('报告.md', f.options), published: string[] = []
    observer.subscribe(() => { const text = observer.getSnapshot().page?.text; if (text) published.push(text) })
    await flush(); f.feeds[0]!.push({ kind: 'ready' }); await flush()
    f.setFile('opaque-v2', 'current'); f.feeds[0]!.push({ kind: 'change', change: { absolutePath: '/synthetic-remote/workspace/报告.md', version: 'opaque-v2' } }); await flush()
    pending.resolve({ ok: true, value: { absolutePath: '/synthetic-remote/workspace/报告.md', version: 'opaque-v1', text: 'late', offset: 1, lines: 1, eof: true } }); await flush()
    expect(published).not.toContain('late'); expect(observer.getSnapshot().page?.text).toBe('current'); observer.dispose(); await observer.closed()
  })
  it('deduplicates identical invalidations while a read is in flight, avoiding observed-read feedback', async () => {
    const f = hostFilesFixture(), pending = deferred<Awaited<ReturnType<typeof f.read>>>()
    f.read.mockImplementationOnce(() => pending.promise)
    const observer = new WorkspaceFileObserver('报告.md', f.options); await flush(); f.feeds[0]!.push({ kind: 'ready' }); await flush()
    for (let i = 0; i < 10; i++) f.feeds[0]!.push({ kind: 'change', change: { absolutePath: '/synthetic-remote/workspace/报告.md', version: 'opaque-v1' } })
    await flush(); expect(observer.getSnapshot().stale).toBe(false); expect(f.read).toHaveBeenCalledTimes(2)
    pending.resolve({ ok: true, value: { absolutePath: '/synthetic-remote/workspace/报告.md', version: 'opaque-v1', text: 'late', offset: 1, lines: 1, eof: true } }); await flush()
    expect(observer.getSnapshot().page?.text).not.toBe('late'); observer.dispose(); await observer.closed()
  })
  it('pins a Host-resolved alias to the same canonical file for watch and reads', async () => {
    const f = hostFilesFixture()
    f.stat.mockResolvedValueOnce({ ok: true, value: { absolutePath: '/synthetic-remote/workspace/canonical.md', version: 'opaque-v1' } })
    const observer = new WorkspaceFileObserver('alias/report.md', f.options); await flush()
    expect(f.changes.mock.calls[0]?.[1]).toBe('/synthetic-remote/workspace/canonical.md')
    f.feeds[0]!.push({ kind: 'ready' }); await flush()
    expect(f.read.mock.calls[0]?.[1]).toBe('/synthetic-remote/workspace/canonical.md')
    f.setFile('v2', 'canonical update'); observer.refresh(); await flush()
    expect(f.stat.mock.calls.slice(1).every(call => call[1] === '/synthetic-remote/workspace/canonical.md')).toBe(true)
    expect(observer.getSnapshot().page?.text).toBe('canonical update'); observer.dispose(); await observer.closed()
  })
  it('deletion clears content; recreation rereads; invalid/foreign frames stop watch instead of guessing', async () => {
    const f = hostFilesFixture(), observer = new WorkspaceFileObserver('报告.md', f.options)
    await flush(); f.feeds[0]!.push({ kind: 'ready' }); await flush()
    f.feeds[0]!.push({ kind: 'change', change: { absolutePath: '/synthetic-remote/workspace/报告.md', absent: true } }); await flush()
    expect(observer.getSnapshot().page).toBeUndefined(); expect(observer.getSnapshot().error).toContain('not-found')
    f.setFile('recreated'); f.feeds[0]!.push({ kind: 'change', change: { absolutePath: '/synthetic-remote/workspace/报告.md', version: 'recreated' } }); await flush(); expect(observer.getSnapshot().page?.version).toBe('recreated')
    f.feeds[0]!.push({ kind: 'change', change: { absolutePath: '/synthetic-remote/workspace/another.md', version: 'other' } }); await flush()
    expect(observer.getSnapshot()).toMatchObject({ mode: 'manual', stale: true, reason: expect.stringContaining('another file') }); expect(f.feeds[0]?.closed).toBe(true)
    observer.dispose(); await observer.closed()
  })
  it('page reads fence version; changes reset to line 1; timeout ready has a real reason', async () => {
    const f = hostFilesFixture(); f.setFile('opaque-v1', 'first', false)
    const observer = new WorkspaceFileObserver('报告.md', f.options); await flush(); f.feeds[0]!.push({ kind: 'ready' }); await flush()
    await observer.nextPage(); expect(f.read.mock.calls.at(-1)?.[2].offset).toBe(3)
    f.setFile('opaque-v2', 'restart'); f.feeds[0]!.push({ kind: 'change', change: { absolutePath: '/synthetic-remote/workspace/报告.md', version: 'opaque-v2' } }); await flush(); expect(f.read.mock.calls.at(-1)?.[2].offset).toBe(1)
    observer.dispose(); await observer.closed()
    vi.useFakeTimers(); const g = hostFilesFixture(), waiting = new WorkspaceFileObserver('报告.md', g.options)
    await flush(); await vi.advanceTimersByTimeAsync(101); await flush()
    expect(waiting.getSnapshot()).toMatchObject({ mode: 'manual', reason: expect.stringContaining('ready') }); waiting.dispose(); await waiting.closed()
  })
  it('two instances isolate lifetimes and never follow another selected Session', async () => {
    const f = hostFilesFixture(), g = hostFilesFixture(), first = new WorkspaceFileObserver('first.md', f.options), second = new WorkspaceFileObserver('second.md', g.options)
    await flush(); first.dispose(); await first.closed(); expect(f.feeds[0]?.closed).toBe(true); expect(g.feeds[0]?.closed).toBe(false)
    g.change({ sessionId: SessionId('synthetic-other') }); await flush(); expect(second.getSnapshot().mode).toBe('closed'); expect(g.feeds).toHaveLength(1); await second.closed()
  })
  it('late watch open after close is disposed; unknown cleanup never opens a successor', async () => {
    const f = hostFilesFixture(), pending = deferred<AsyncIterable<unknown>>()
    const dispose = vi.fn(), returned = vi.fn(async () => ({ done: true as const, value: undefined }))
    f.changes.mockImplementationOnce(() => pending.promise)
    const observer = new WorkspaceFileObserver('报告.md', f.options); await flush()
    f.change({ ready: false }); await flush(); f.change({ ready: true, generation: 2 }); await flush()
    expect(f.changes).toHaveBeenCalledTimes(1); expect(observer.getSnapshot().reason).toContain('cleanup')
    observer.dispose(); await expect(observer.closed()).rejects.toThrow('unknown')
    const late = { dispose, [Symbol.asyncIterator]: () => ({ next: async () => ({ done: true, value: undefined }), return: returned }) }
    pending.resolve(late); await flush()
    expect(dispose).toHaveBeenCalledTimes(1); expect(returned).toHaveBeenCalledTimes(1); await observer.closed(); expect(observer.getSnapshot().mode).toBe('closed')
  })
})
